djangoProject/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from djangoProject.views import redirect_main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('account/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', redirect_main),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from news.views import AddNews, AllNews, DeleteNews, DetailCategory, DetailNews, DetailUserNews, EditNews, Feedback

app_name = 'news'
urlpatterns = [
    path('', AllNews.as_view(), name='all_news'),
    path('<int:pk>/', DetailNews.as_view(), name='detail_news'),
    path('<int:category_id>', DetailCategory.as_view(), name='detail_category'),
    path('user/<int:user_id>/news', DetailUserNews.as_view(), name='detail_user_news'),
    path('add_news/', AddNews.as_view(), name='add_news'),
    path('edit/<int:pk>/', EditNews.as_view(), name='edit_news'),
    path('delete/<int:pk>/', DeleteNews.as_view(), name='delete_news'),
    path('feedback/', Feedback.as_view(), name='feedback'),
]

news/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class News(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='автор', default=None)
    title = models.CharField(max_length=150, verbose_name='заголовок')
    content = models.TextField(verbose_name='текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата обновления')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='постер', default='photos/default.svg')
    is_published = models.BooleanField(default=True, verbose_name='статус публикации')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='категория', db_index=True, default=None)
    audio = models.FileField(upload_to='audio/%Y/%m/%d/', verbose_name='аудио', blank=True)

    def get_absolute_url(self):
        return reverse('news:detail_news', kwargs={'pk': self.pk})

    def __str__(self):
        return f"Заголовок новости:  {self.title}"

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'
        ordering = ['created_at', 'title']


class Category(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок', unique=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('news:detail_category', kwargs={'category_id': self.pk})


class Comment(models.Model):
    news = models.ForeignKey('News', on_delete=models.PROTECT, verbose_name='новость')
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='автор')
    content = models.TextField(verbose_name='текст')
    pub_date = models.DateTimeField(verbose_name='дата', auto_now_add=True)

    def __str__(self):
        return self.content[0:200]

news/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms

from news.models import News


class AddNewsForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget(), label='Контент')

    class Meta:
        model = News
        fields = ['title', 'content', 'photo', 'is_published', 'category', 'audio']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control-file', 'type': 'file'}),
            'audio': forms.FileInput(attrs={'class': 'form-control-file', 'type': 'file'}),
        }


class FeedbackForm(forms.Form):
    subject = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Тута тема обращения'}), max_length=150, label='Тема')
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Тута контент обращения', 'rows': 5}), label='Контент')

news/views.py
# Create your views here.
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from news.forms import AddNewsForm, FeedbackForm
from news.models import Category, News


class AllNews(ListView):
    """
    Выводит список всех новостей на главной странице
    Модель: News
    Шаблон: 'news/all_news.html'
    Ключ в контексте: 'all_news'
    Количество новостей на одной странице: 4
    Запрос: Объект News с фильтрацией по статусу публикации, при этом используется "жадное присоединение" полей "category","author"
    и сортировка, чтобы самые свежие новости были сверху
    """
    model = News
    template_name = 'news/all_news.html'
    context_object_name = 'all_news'
    paginate_by = 4
    queryset = News.objects.filter(is_published=True).select_related('category', 'author').order_by('-created_at')
    allow_empty = False


class DetailCategory(ListView):
    """
    Выводит список новостей по определённой категории
    """
    model = News
    template_name = 'news/detail_category.html'
    context_object_name = 'detail_category'
    paginate_by = 4
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DetailCategory, self).get_context_data(**kwargs)
        context['title_category'] = Category.objects.get(pk=self.kwargs['category_id']).title
        return context

    def get_queryset(self):
        return News.objects.filter(category=self.kwargs['category_id'], is_published=True).select_related('author').order_by('-created_at')


class DetailUserNews(ListView):
    """
    Выводит список всех новостей у определённого пользователя
    """
    model = News
    template_name = 'news/detail_user_news.html'
    context_object_name = 'detail_user_news'
    paginate_by = 4
    allow_empty = False

    def get_queryset(self):
        return News.objects.filter(author=self.kwargs['user_id'], is_published=True).select_related('category').order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DetailUserNews, self).get_context_data(**kwargs)
        # context['author_name'] = News.objects.filter(author=self.kwargs['user_id'])[0].author.username
        context['author_name'] = User.objects.filter(pk=self.kwargs['user_id'])[0]
        return context


class DetailNews(DetailView):
    """
    Выводит одну новость со всей информацией о ней
    """
    model = News
    template_name = 'news/detail_news.html'
    context_object_name = 'detail_news'

    def get_queryset(self):
        model = News.objects.select_related('category', 'author').get(pk=self.kwargs['pk'])
        if self.request.user.id == model.author.id:
            return News.objects.filter(pk=self.kwargs['pk']).select_related('category', 'author')
        else:
            return News.objects.filter(pk=self.kwargs['pk'], is_published=True).select_related('category', 'author')


class AddNews(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Выводит форму для создания новости
    """
    model = News
    form_class = AddNewsForm
    template_name = 'news/add_news.html'
    login_url = reverse_lazy('account:login')
    success_message = "Новость успешна создана"
    queryset = News.objects.select_related('category')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(AddNews, self).form_valid(form)


class EditNews(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    """
    Выводит форму для редактирования существующих новостей
    """
    model = News
    form_class = AddNewsForm
    template_name = 'news/edit_news.html'
    context_object_name = 'news'
    success_message = 'Ваша новость успешно отредактирована'
    login_url = reverse_lazy('account:login')

    def test_func(self):
        obj = self.get_object()
        return obj.author.id == self.request.user.id


class DeleteNews(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = News
    success_message = 'Ваша новость успешно удалена'
    template_name = 'news/delete_news.html'
    login_url = reverse_lazy('account:login')
    context_object_name = 'delete_news'
    success_url = reverse_lazy('news:all_news')

    def test_func(self):
        obj = self.get_object()
        return obj.author.id == self.request.user.id


class Feedback(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Выводит форму для отправки обращения на почту
    """
    form_class = FeedbackForm
    template_name = 'news/feedback.html'
    login_url = reverse_lazy('account:login')

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            mail = send_mail(subject=f"{form.cleaned_data['subject']}(id = {request.user.id}, username = {request.user.username})", message=form.cleaned_data['content'],
                             from_email=request.user.email, recipient_list=settings.EMAIL_HOST_USER.split(' '), fail_silently=False)
            if mail:
                messages.success(request, 'Ваше обращение успешно отправлено')
                messages.success(request, 'Спасибо за ваш отзыв')
                return redirect('news:feedback')
            else:
                messages.error(request, 'Ошибка при отправке письма')
                return render(request, template_name=self.template_name, context={'form': form})

news/templates/news/add_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Создать новость
{% endblock %}

{% block content %}
    <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
        <form action="{% url 'news:add_news' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-block">Добавить новость</button>
        </form>
    </div>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

news/templates/news/all_news.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
    Новости для королей
{% endblock %}
{% block content %}
    {#navbar#}
    {#endnavbar#}
    {#content#}
    <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
            <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
            <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most
                interesting in this post’s contents.</p>
            <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
        </div>
    </div>

    <div class="row row-cols-2">
        {% for new in all_news %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="bd-placeholder-img card-img-top" focusable="false" role="img"
                         width="100%" height="100%" src="{{ new.photo.url }}" alt="{{ new.photo.name }}">
                    <div class="card-body">
                        <h3 class="card-text">{{ new.title }}</h3>
                        <hr>
                        <a style="text-decoration: none;" href="{% url 'news:detail_user_news' new.author_id %}"><p>{{ new.author }}</p></a>
                        <hr>
                        <a style="text-decoration: none;" href="{{ new.category.get_absolute_url }}"><p>{{ new.category.title }}</p></a>
                        <div class="d-flex justify-content-between align-items-center">

                            <div class="btn-group">
                                <form action="{{ new.get_absolute_url }}">
                                    <button type="submit" class="btn btn-sm btn-outline-secondary">
                                        Читать далее
                                    </button>
                                </form>
                            </div>
                            <small class="text-muted">{{ new.created_at|naturaltime }}</small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        {% include 'inc/_paginator.html' %}
    </div>
    {#endcontent#}
{% endblock %}

news/templates/news/delete_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Редактировать новость
{% endblock %}

{% block content %}
    <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
        <form method="post">
            {% csrf_token %}
            <h1 class="display-4">Вы уверены, что хотите удалить новость: "{{ delete_news.title }}"?</h1>
            <button type="submit" class="btn btn-success">Подтвердить</button>
            <a class="btn btn-danger" href="{% url 'news:detail_user_news' delete_news.author_id %}"
               role="button">Отменить</a>
        </form>
    </div>
{% endblock %}

news/templates/news/detail_category.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
    {{ title_category }}
{% endblock %}
{% block content %}
    {#navbar#}
    {#endnavbar#}
    {#content#}
    <h1 class="display-4">{{ title_category }}</h1>

    <div class="row row-cols-2">
        {% for category in detail_category %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="bd-placeholder-img card-img-top" focusable="false" role="img"
                         width="100%" height="100%" src="{{ category.photo.url }}" alt="{{ category.photo.name }}">
                    <div class="card-body">
                        <h3 class="card-text">{{ category.title }}</h3>
                        <hr>
                        <a style="text-decoration: none;" href="#"><p>{{ category.author }}</p></a>
                        <hr>
                        <div class="d-flex justify-content-between align-items-center">

                            <div class="btn-group">
                                <form action="{{ category.get_absolute_url }}">
                                    <button type="submit" class="btn btn-sm btn-outline-secondary">
                                        Читать далее
                                    </button>
                                </form>
                            </div>
                            <small class="text-muted">{{ category.created_at|naturaltime }}</small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {#endcontent#}
    <br>
    {% include 'inc/_paginator.html' %}
{% endblock %}

news/templates/news/detail_news.html
{% extends 'base.html' %}
{% block title %}
    {{ detail_news.title }}
{% endblock %}
{% block content %}
    {#navbar#}
    {#endnavbar#}
    {#content#}
    <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
        <h1 class="display-4">{{ detail_news.title }}</h1>
        <p class="lead mb-">Автор: <a style="text-decoration: none;" href="{{ detail_news.author.profile.get_absolute_url }}"
                                      class="text-white font-weight-bold">{{ detail_news.author }}</a></p>
        <p class="lead mb-">Категория: <a style="text-decoration: none;" href="{{ detail_news.category.get_absolute_url }}"
                                          class="text-white font-weight-bold">{{ detail_news.category.title }}</a></p>
        <p class="lead mb-">Дата публикации: {{ detail_news.created_at }}</p>
        {% if detail_news.audio %}
            <audio controls>
                <source src="{{ detail_news.audio.url }}" type="audio/mpeg">
                Тег audio не поддерживается вашим браузером.
                <a href="{{ detail_news.audio.url }}">Скачайте музыку</a>.
            </audio>
        {% else %}

        {% endif %}

        <hr style="color: #ffffff;">
        <h4 class="display-5">{{ detail_news.content|safe }}</h4>
    </div>
    {#endcontent#}
{% endblock %}

news/templates/news/detail_user_news.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
    Новости {{ author_name }}
{% endblock %}
{% block content %}
    {#navbar#}
    {#endnavbar#}
    {#content#}
    <h1 class="display-4">{{ author_name }}</h1>


    <div class="row row-cols-2">

        {% for user_news in detail_user_news %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="bd-placeholder-img card-img-top" focusable="false" role="img"
                         width="100%" height="100%" src="{{ user_news.photo.url }}" alt="{{ user_news.photo.name }}">
                    <div class="card-body">
                        <h3 class="card-text">{{ user_news.title }}</h3>
                        <hr>
                        <a style="text-decoration: none;" href="{{ user_news.category.get_absolute_url }}"><p>{{ user_news.category }}</p>
                        </a>
                        <hr>
                        <div class="d-flex justify-content-between align-items-center">

                            <div class="btn-group">
                                {% if author_name.id == request.user.id %}
                                    <a class="btn btn-sm btn-outline-secondary" href="{{ user_news.get_absolute_url }}" role="button">Читать
                                        далее</a>
                                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'news:edit_news' user_news.pk %}"
                                       role="button">Редактировать</a>
                                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'news:delete_news' user_news.pk %}"
                                       role="button">Удалить</a>
                                {% else %}
                                    <a class="btn btn-sm btn-outline-secondary" href="{{ user_news.get_absolute_url }}" role="button">Читать
                                        далее</a>
                                {% endif %}
                            </div>
                            <small class="text-muted">{{ user_news.created_at|naturaltime }}</small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {#endcontent#}
    <br>
    {% include 'inc/_paginator.html' %}
{% endblock %}

news/templates/news/edit_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Редактировать новость
{% endblock %}

{% block content %}
    {#    {% if news.author_id == request.user.id %}#}
    <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field.errors }}
            {#title#}
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">Название: </label>
                {{ form.title }}
                <div class="invalid-feedback">
                    {{ form.title.errors }}
                </div>
            </div>
            {#end title#}
            {#content#}
            <div class="form-group">
                <label for="{{ form.content.id_for_label }}">Контент: </label>
                <br>
                {{ form.content }}
                <div class="invalid-feedback">
                    {{ form.content.errors }}
                </div>
            </div>
            {#end content#}
            {#photo#}
            <div class="form-group">
                <label for="{{ form.photo.id_for_label }}">Постер: </label>
                <br>
                {{ form.photo }}
                <div class="invalid-feedback">
                    {{ form.photo.errors }}
                </div>
            </div>
            {#end photo#}
            {#is_published#}
            <div class="form-group">
                <label for="{{ form.is_published.id_for_label }}">Опубликовать? </label>
                {{ form.is_published }}
                <div class="invalid-feedback">
                    {{ form.is_published.errors }}
                </div>
            </div>
            {#end is_published#}
            {#category#}
            <div class="form-group">
                <label for="{{ form.category.id_for_label }}">Категория: </label>
                {{ form.category }}
                <div class="invalid-feedback">
                    {{ form.category.errors }}
                </div>
            </div>
            <div class="form-group">
                <label for="{{ form.audio.id_for_label }}">Аудио: </label>
                <br>
                {{ form.audio }}
                <div class="invalid-feedback">
                    {{ form.audio.errors }}
                </div>
            </div>
            {#end category#}
            <button type="submit" class="btn btn-primary btn-block">Сохранить новость</button>
        </form>
    </div>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

news/templates/news/feedback.html
{% extends 'base.html' %}

{% block title %}
    Обратная связь
{% endblock %}

{% block content %}
    <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
        <form action="{% url 'news:feedback' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-block">Отправить сообщещие</button>
        </form>
    </div>
{% endblock %}