account/urls.py
from django.urls import path

from account.views import EditProfileAccount, LoginAccount, LogoutAccount, ProfileAccount, RegisterAccount

app_name = 'account'
urlpatterns = [
    path('register/', RegisterAccount.as_view(), name='register'),
    path('login/', LoginAccount.as_view(), name='login'),
    path('logout/', LogoutAccount.as_view(), name='logout'),
    path('user/<int:pk>/', ProfileAccount.as_view(), name='profile_user'),
    path('user/<int:user_id>/edit/', EditProfileAccount.as_view(), name='edit_profile'),
]

djangoProject/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from djangoProject.views import redirect_main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('account/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', redirect_main),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from news.views import AddNews, AllNews, DeleteNews, DetailCategory, DetailNews, DetailUserNews, EditNews, Feedback

app_name = 'news'
urlpatterns = [
    path('', AllNews.as_view(), name='all_news'),
    path('<int:pk>/', DetailNews.as_view(), name='detail_news'),
    path('<int:category_id>', DetailCategory.as_view(), name='detail_category'),
    path('user/<int:user_id>/news', DetailUserNews.as_view(), name='detail_user_news'),
    path('add_news/', AddNews.as_view(), name='add_news'),
    path('edit/<int:pk>/', EditNews.as_view(), name='edit_news'),
    path('delete/<int:pk>/', DeleteNews.as_view(), name='delete_news'),
    path('feedback/', Feedback.as_view(), name='feedback'),
]

templates/inc/_nav.html
{% load news_tags %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffffff;">
    <a class="navbar-brand" href="{% url 'news:all_news' %}">👑King News👑</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'news:add_news' %}">🖊 Добавить новость<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    🗃 Категории
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% get_list_category as categories %}
                    {% for c in categories %}
                        <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.title }}<span
                                class="badge badge-light">{{ c.cnt }}</span></a>
                    {% endfor %}
                </div>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        💼 Добро пожаловать, {{ user.username }}!
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'account:profile_user' request.user.id %}">Мой профиль</a>
                        <a class="dropdown-item" href="{% url 'news:detail_user_news' request.user.id %}">Мои новости</a>
                        <a class="dropdown-item" href="{% url 'news:feedback' %}">Обратная связь</a>
                        <a class="dropdown-item" href="{% url 'account:logout' %}">Выйти</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        💼 Аккаунт
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'account:login' %}?next={{ request.path }}">Авторизация</a>
                        <a class="dropdown-item" href="{% url 'account:register' %}">Регистрация</a>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/inc/_paginator.html
<div class="container">
    <br>
    <div class="pagination-area pb-45 text-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="single-wrap d-flex justify-content-center">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-start">
                                {% if is_paginated %}
                                    {% if page_obj.has_previous %}
                                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">«</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled"><span class="page-link">«</span></li>
                                    {% endif %}
                                    {% for i in paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active"><span class="page-link">{{ i }} <span class="page-link sr-only">(current)</span></span>
                                            </li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">»</a></li>
                                    {% else %}
                                        <li class="page-item disabled"><span class="page-link">»</span></li>
                                    {% endif %}
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>